Bak/Car/car_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cars/', include('cars.urls')),
]

Bak/Office/my_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('office/', include('office.urls'))
]

classroom/urls.py
from django.urls import path
from .views import HomeView, ThanksView, ContactFormView, \
    TeacherCreateView, TeacherListView, TeacherDetailView, \
    TeacherUpdateView, TeacherDeleteView

app_name = 'classroom'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('thanks/', ThanksView.as_view(), name='thanks'),
    path('contact/', ContactFormView.as_view(), name='contact'),
    path('addteacher/', TeacherCreateView.as_view(), name='add-teacher'),
    path('teachers/', TeacherListView.as_view(), name='teacher-list'),
    path('teachers/<int:pk>', TeacherDetailView.as_view(), name='teacher-detail'),
    path('teachers/<int:pk>/update', TeacherUpdateView.as_view(), name='teacher-update'),
    path('teachers/<int:pk>/delete', TeacherDeleteView.as_view(), name='teacher-delete')
]

school/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('classroom/', include('classroom.urls'))
]

classroom/models.py
from django.db import models


# Create your models here.
class Teacher(models.Model):
    first_name = models.CharField(max_length=15)
    last_name = models.CharField(max_length=15)
    subject = models.CharField(max_length=30)

    def __str__(self):
        return f'{self.first_name} {self.last_name} | {self.subject}'


class Reviews(models.Model):
    name = models.CharField(max_length=30)
    message = models.CharField(max_length=200)

    def __str__(self):
        return f"{self.name}'s review"

classroom/forms.py
from django import forms
from .models import Reviews


class ContactForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

classroom/views.py
from django.views.generic import TemplateView, \
    FormView, CreateView, ListView, DetailView, \
    UpdateView, DeleteView
from django.urls import reverse_lazy
from classroom.models import Teacher, Reviews
from .forms import ContactForm


# Create your views here.
class HomeView(TemplateView):
    template_name = 'classroom/home.html'


class ThanksView(TemplateView):
    template_name = 'classroom/thanks.html'


class TeacherCreateView(CreateView):
    # CreateView auto looking for model_form.html
    model = Teacher
    fields = '__all__'
    success_url = reverse_lazy('classroom:teacher-list')


class ContactFormView(FormView):
    form_class = ContactForm
    template_name = 'classroom/contact.html'

    # success_url = '/classroom/thanks'
    success_url = reverse_lazy('classroom:thanks')

    def form_valid(self, form):
        print(form.cleaned_data['message'])
        Reviews.objects.create(name=form.cleaned_data['name'], message=form.cleaned_data['message'])
        return super().form_valid(form)


class TeacherListView(ListView):
    model = Teacher
    context_object_name = 'teachers'


class TeacherDetailView(DetailView):
    model = Teacher


class TeacherUpdateView(UpdateView):
    model = Teacher
    fields = "__all__"
    success_url = reverse_lazy('classroom:teacher-list')


class TeacherDeleteView(DeleteView):
    model = Teacher
    success_url = reverse_lazy('classroom:teacher-list')

classroom/templates/classroom/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Form</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>
</body>
</html>

classroom/templates/classroom/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Home HTML</h1>
<ul>
    <li>
        <a href="{% url 'classroom:thanks' %}">Thanks</a>
    </li>
    <li>
        <a href="{% url 'classroom:contact' %}">Contact</a>
    </li>
    <li>
        <a href="{% url 'classroom:add-teacher' %}">Add Teacher</a>
    </li>
    <li>
        <a href="{% url 'classroom:teacher-list' %}">Teacher List</a>
    </li>
</ul>
</body>
</html>

classroom/templates/classroom/teacher_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Are You Sure You Want To Delete?</h1>
<h3>{{ teacher }}</h3>
<form method="POST">
    {% csrf_token %}
    <input type="submit" value="Confirm Delete">
</form>
</body>
</html>

classroom/templates/classroom/teacher_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{ teacher }}</h1>
<a href="{{ teacher.id }}/update">Update</a>
<a href="{{ teacher.id }}/delete">Delete</a>
</body>
</html>

classroom/templates/classroom/teacher_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Teacher Form</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>
</body>
</html>

classroom/templates/classroom/teacher_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>List Teacher</h1>
<ul>
    {% for teacher in teachers %}
        <a href='{{ teacher.id }}'>
            <li>{{ teacher.first_name }} {{ teacher.last_name }}</li>
        </a>
    {% endfor %}
</ul>
</body>
</html>

classroom/templates/classroom/thanks.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Thanks</h1>
</body>
</html>