Bak/Car/car_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cars/', include('cars.urls')),
]

Bak/First/new_app/urls.py
from django.urls import path
from . import views

app_name = 'new_app'

urlpatterns = [
    path('', views.new_index, name='index'),
    path('variable', views.variable_view, name='variable'),
    path('new-page', views.new_page, name='new-page')
]

Bak/Office/my_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('office/', include('office.urls'))
]

school/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('classroom/', include('classroom.urls'))
]

Bak/First/new_app/models.py
from django.db import models

# Create your models here.

Bak/First/DjangoLeaning/views.py
from django.shortcuts import render


# Custom 404-Page In Django
# def my_custom_page_not_found(req, exception):
#     return render(req, 'error_page.html', status=404)

Bak/First/new_app/views.py
from django.shortcuts import render


# Create your views here.
def new_index(req):
    return render(req, 'new_app/index.html')


def variable_view(req):
    my_var = {'first_name': 'Rosalind', 'last_name': 'Jon',
              'some_list': [81, 22, 3, 24, 18, 67, 45, 100],
              'some_dict': {'call_phone': 10080215}, 'user_login': True}

    return render(req, 'new_app/variable.html', context=my_var)


def new_page(req):
    return render(req, 'new_app/newpage.html')

Bak/First/templates/new_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>This is a H1 and new_app page</h1>
<a href="{% url 'new_app:variable' %}">Click me</a>
</body>
</html>

Bak/First/templates/new_app/variable.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Variable</title>
</head>
<body>
<h1>Variable</h1>
<h2>First Name: {{ first_name | capfirst }}, Last Name: {{ last_name | capfirst }}</h2>
<h3>
    {% for item in some_list %}
    {{ item }}
    {% endfor %}
</h3>
<p>
    {% if user_login %}
    Welcome back you are in
    {% endif %}
</p>
</body>
</html>